package com.cryptowallet.simulator;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(value = "/wallet")
public class WalletController {

    @GetMapping(value = "/test")
    public String test() {
        return "Test wallet service";
    }

    // all crypto currencies with prices
    // https://min-api.cryptocompare.com/data/blockchain/list
    // list of all crypto currencies from crypto compare api but no prices
    // id and symbol
    // best way I think we should return a list of symbols

    // create a wallet
    /*
       Input: id(autogenerated value) friendlyName and initial values(currency and available amount in the wallet)
     */

    // get a wallet

    // update a wallet

    // delete a wallet

    // buy a currency
    /*
       Input: to wallet: from currency with amount i want to buy a currency
     */

    // transfer currencies between two wallets
    /*
       Input: from wallet: amount and currency, to wallet: currency
     */
}
